# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2019-01-25 21:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_id', models.CharField(max_length=255)),
                ('race', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('etat', models.CharField(max_length=255)),
                ('lieu', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Equipement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lieu', models.CharField(max_length=255)),
                ('disponibilite', models.CharField(max_length=255)),
            ],
        ),
    ]
